### ISSUE TITLE
Rename fidisys-expandable-card to expandable-card

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [fidisys/react-native-components#1]
Since we are adopting lerna the package name at result will be ``@fidisys/expandable-card`` so we don't need to have the name again in the `package.json` file

The package which needs to be re-named --> https://github.com/fidisys/React-Native-Components/tree/master/packages/fidisys-expandable-card

**Comment by JuanVqz** [comment]
Hi I created a pr #11 but it has a failure, `Manifest not found`, I can fix but what manifest? thanks!
