### ISSUE TITLE
Setup commitizen for maintaining conventional commit message

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [fidisys/react-native-components#3]
Commitizen --> https://github.com/commitizen/cz-cli

**Comment by geekyrajshri** [comment]
Hi,
I would like to do this

**Comment by JayaKrishnaNamburu** [comment]
Sure 👍

**Comment by geekyrajshri** [comment]
Hey @JayaKrishnaNamburu 
I have setup commitizen as part of husky precommit. Will that work?
